/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSystemFlowRouteImport } from './routes/_authenticated.system-flow'
import { Route as AuthenticatedSubtasksRouteImport } from './routes/_authenticated.subtasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated.services'
import { Route as AuthenticatedRoutingDecisionsRouteImport } from './routes/_authenticated.routing-decisions'
import { Route as AuthenticatedRequestsEngineRouteImport } from './routes/_authenticated.requests-engine'
import { Route as AuthenticatedRegistryRouteImport } from './routes/_authenticated.registry'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated.providers'
import { Route as AuthenticatedOrchestratorRouteImport } from './routes/_authenticated.orchestrator'
import { Route as AuthenticatedOrchestrationRouteImport } from './routes/_authenticated.orchestration'
import { Route as AuthenticatedNetworkRouteImport } from './routes/_authenticated.network'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated.monitoring'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated.knowledge'
import { Route as AuthenticatedInternalConnectorsRouteImport } from './routes/_authenticated.internal-connectors'
import { Route as AuthenticatedFallbackRulesRouteImport } from './routes/_authenticated.fallback-rules'
import { Route as AuthenticatedDiscoveryRouteImport } from './routes/_authenticated.discovery'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedApiConsoleRouteImport } from './routes/_authenticated.api-console'
import { Route as AuthenticatedSitesIndexRouteImport } from './routes/_authenticated.sites.index'
import { Route as AuthenticatedPipelinesIndexRouteImport } from './routes/_authenticated.pipelines.index'
import { Route as AuthenticatedSitesSlugRouteImport } from './routes/_authenticated.sites.$slug'
import { Route as AuthenticatedPipelinesIdRouteImport } from './routes/_authenticated.pipelines.$id'
import { Route as ApiPublicV1PipelineRouteImport } from './routes/api/public/v1/pipeline'
import { Route as ApiPublicV1OrchestrateRouteImport } from './routes/api/public/v1/orchestrate'
import { Route as ApiPublicV1ExecuteRouteImport } from './routes/api/public/v1/execute'
import { Route as ApiPublicV1AskRouteImport } from './routes/api/public/v1/ask'
import { Route as ApiPublicV1OrchestrateIdRouteImport } from './routes/api/public/v1/orchestrate.$id'
import { Route as ApiPublicV1DiscoveryRefreshRouteImport } from './routes/api/public/v1/discovery.refresh'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSystemFlowRoute = AuthenticatedSystemFlowRouteImport.update({
  id: '/system-flow',
  path: '/system-flow',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubtasksRoute = AuthenticatedSubtasksRouteImport.update({
  id: '/subtasks',
  path: '/subtasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutingDecisionsRoute =
  AuthenticatedRoutingDecisionsRouteImport.update({
    id: '/routing-decisions',
    path: '/routing-decisions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRequestsEngineRoute =
  AuthenticatedRequestsEngineRouteImport.update({
    id: '/requests-engine',
    path: '/requests-engine',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRegistryRoute = AuthenticatedRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrchestratorRoute =
  AuthenticatedOrchestratorRouteImport.update({
    id: '/orchestrator',
    path: '/orchestrator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrchestrationRoute =
  AuthenticatedOrchestrationRouteImport.update({
    id: '/orchestration',
    path: '/orchestration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNetworkRoute = AuthenticatedNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInternalConnectorsRoute =
  AuthenticatedInternalConnectorsRouteImport.update({
    id: '/internal-connectors',
    path: '/internal-connectors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFallbackRulesRoute =
  AuthenticatedFallbackRulesRouteImport.update({
    id: '/fallback-rules',
    path: '/fallback-rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiscoveryRoute = AuthenticatedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiConsoleRoute = AuthenticatedApiConsoleRouteImport.update({
  id: '/api-console',
  path: '/api-console',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitesIndexRoute = AuthenticatedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelinesIndexRoute =
  AuthenticatedPipelinesIndexRouteImport.update({
    id: '/pipelines/',
    path: '/pipelines/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSitesSlugRoute = AuthenticatedSitesSlugRouteImport.update({
  id: '/sites/$slug',
  path: '/sites/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelinesIdRoute =
  AuthenticatedPipelinesIdRouteImport.update({
    id: '/pipelines/$id',
    path: '/pipelines/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicV1PipelineRoute = ApiPublicV1PipelineRouteImport.update({
  id: '/api/public/v1/pipeline',
  path: '/api/public/v1/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OrchestrateRoute = ApiPublicV1OrchestrateRouteImport.update({
  id: '/api/public/v1/orchestrate',
  path: '/api/public/v1/orchestrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ExecuteRoute = ApiPublicV1ExecuteRouteImport.update({
  id: '/api/public/v1/execute',
  path: '/api/public/v1/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AskRoute = ApiPublicV1AskRouteImport.update({
  id: '/api/public/v1/ask',
  path: '/api/public/v1/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OrchestrateIdRoute =
  ApiPublicV1OrchestrateIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicV1OrchestrateRoute,
  } as any)
const ApiPublicV1DiscoveryRefreshRoute =
  ApiPublicV1DiscoveryRefreshRouteImport.update({
    id: '/api/public/v1/discovery/refresh',
    path: '/api/public/v1/discovery/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api-console': typeof AuthenticatedApiConsoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/fallback-rules': typeof AuthenticatedFallbackRulesRoute
  '/internal-connectors': typeof AuthenticatedInternalConnectorsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/orchestration': typeof AuthenticatedOrchestrationRoute
  '/orchestrator': typeof AuthenticatedOrchestratorRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/requests-engine': typeof AuthenticatedRequestsEngineRoute
  '/routing-decisions': typeof AuthenticatedRoutingDecisionsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subtasks': typeof AuthenticatedSubtasksRoute
  '/system-flow': typeof AuthenticatedSystemFlowRoute
  '/pipelines/$id': typeof AuthenticatedPipelinesIdRoute
  '/sites/$slug': typeof AuthenticatedSitesSlugRoute
  '/pipelines/': typeof AuthenticatedPipelinesIndexRoute
  '/sites/': typeof AuthenticatedSitesIndexRoute
  '/api/public/v1/ask': typeof ApiPublicV1AskRoute
  '/api/public/v1/execute': typeof ApiPublicV1ExecuteRoute
  '/api/public/v1/orchestrate': typeof ApiPublicV1OrchestrateRouteWithChildren
  '/api/public/v1/pipeline': typeof ApiPublicV1PipelineRoute
  '/api/public/v1/discovery/refresh': typeof ApiPublicV1DiscoveryRefreshRoute
  '/api/public/v1/orchestrate/$id': typeof ApiPublicV1OrchestrateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api-console': typeof AuthenticatedApiConsoleRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/fallback-rules': typeof AuthenticatedFallbackRulesRoute
  '/internal-connectors': typeof AuthenticatedInternalConnectorsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/network': typeof AuthenticatedNetworkRoute
  '/orchestration': typeof AuthenticatedOrchestrationRoute
  '/orchestrator': typeof AuthenticatedOrchestratorRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/requests-engine': typeof AuthenticatedRequestsEngineRoute
  '/routing-decisions': typeof AuthenticatedRoutingDecisionsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subtasks': typeof AuthenticatedSubtasksRoute
  '/system-flow': typeof AuthenticatedSystemFlowRoute
  '/pipelines/$id': typeof AuthenticatedPipelinesIdRoute
  '/sites/$slug': typeof AuthenticatedSitesSlugRoute
  '/pipelines': typeof AuthenticatedPipelinesIndexRoute
  '/sites': typeof AuthenticatedSitesIndexRoute
  '/api/public/v1/ask': typeof ApiPublicV1AskRoute
  '/api/public/v1/execute': typeof ApiPublicV1ExecuteRoute
  '/api/public/v1/orchestrate': typeof ApiPublicV1OrchestrateRouteWithChildren
  '/api/public/v1/pipeline': typeof ApiPublicV1PipelineRoute
  '/api/public/v1/discovery/refresh': typeof ApiPublicV1DiscoveryRefreshRoute
  '/api/public/v1/orchestrate/$id': typeof ApiPublicV1OrchestrateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/api-console': typeof AuthenticatedApiConsoleRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discovery': typeof AuthenticatedDiscoveryRoute
  '/_authenticated/fallback-rules': typeof AuthenticatedFallbackRulesRoute
  '/_authenticated/internal-connectors': typeof AuthenticatedInternalConnectorsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/network': typeof AuthenticatedNetworkRoute
  '/_authenticated/orchestration': typeof AuthenticatedOrchestrationRoute
  '/_authenticated/orchestrator': typeof AuthenticatedOrchestratorRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRoute
  '/_authenticated/registry': typeof AuthenticatedRegistryRoute
  '/_authenticated/requests-engine': typeof AuthenticatedRequestsEngineRoute
  '/_authenticated/routing-decisions': typeof AuthenticatedRoutingDecisionsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subtasks': typeof AuthenticatedSubtasksRoute
  '/_authenticated/system-flow': typeof AuthenticatedSystemFlowRoute
  '/_authenticated/pipelines/$id': typeof AuthenticatedPipelinesIdRoute
  '/_authenticated/sites/$slug': typeof AuthenticatedSitesSlugRoute
  '/_authenticated/pipelines/': typeof AuthenticatedPipelinesIndexRoute
  '/_authenticated/sites/': typeof AuthenticatedSitesIndexRoute
  '/api/public/v1/ask': typeof ApiPublicV1AskRoute
  '/api/public/v1/execute': typeof ApiPublicV1ExecuteRoute
  '/api/public/v1/orchestrate': typeof ApiPublicV1OrchestrateRouteWithChildren
  '/api/public/v1/pipeline': typeof ApiPublicV1PipelineRoute
  '/api/public/v1/discovery/refresh': typeof ApiPublicV1DiscoveryRefreshRoute
  '/api/public/v1/orchestrate/$id': typeof ApiPublicV1OrchestrateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api-console'
    | '/dashboard'
    | '/discovery'
    | '/fallback-rules'
    | '/internal-connectors'
    | '/knowledge'
    | '/monitoring'
    | '/network'
    | '/orchestration'
    | '/orchestrator'
    | '/providers'
    | '/registry'
    | '/requests-engine'
    | '/routing-decisions'
    | '/services'
    | '/settings'
    | '/subtasks'
    | '/system-flow'
    | '/pipelines/$id'
    | '/sites/$slug'
    | '/pipelines/'
    | '/sites/'
    | '/api/public/v1/ask'
    | '/api/public/v1/execute'
    | '/api/public/v1/orchestrate'
    | '/api/public/v1/pipeline'
    | '/api/public/v1/discovery/refresh'
    | '/api/public/v1/orchestrate/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api-console'
    | '/dashboard'
    | '/discovery'
    | '/fallback-rules'
    | '/internal-connectors'
    | '/knowledge'
    | '/monitoring'
    | '/network'
    | '/orchestration'
    | '/orchestrator'
    | '/providers'
    | '/registry'
    | '/requests-engine'
    | '/routing-decisions'
    | '/services'
    | '/settings'
    | '/subtasks'
    | '/system-flow'
    | '/pipelines/$id'
    | '/sites/$slug'
    | '/pipelines'
    | '/sites'
    | '/api/public/v1/ask'
    | '/api/public/v1/execute'
    | '/api/public/v1/orchestrate'
    | '/api/public/v1/pipeline'
    | '/api/public/v1/discovery/refresh'
    | '/api/public/v1/orchestrate/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/api-console'
    | '/_authenticated/dashboard'
    | '/_authenticated/discovery'
    | '/_authenticated/fallback-rules'
    | '/_authenticated/internal-connectors'
    | '/_authenticated/knowledge'
    | '/_authenticated/monitoring'
    | '/_authenticated/network'
    | '/_authenticated/orchestration'
    | '/_authenticated/orchestrator'
    | '/_authenticated/providers'
    | '/_authenticated/registry'
    | '/_authenticated/requests-engine'
    | '/_authenticated/routing-decisions'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/subtasks'
    | '/_authenticated/system-flow'
    | '/_authenticated/pipelines/$id'
    | '/_authenticated/sites/$slug'
    | '/_authenticated/pipelines/'
    | '/_authenticated/sites/'
    | '/api/public/v1/ask'
    | '/api/public/v1/execute'
    | '/api/public/v1/orchestrate'
    | '/api/public/v1/pipeline'
    | '/api/public/v1/discovery/refresh'
    | '/api/public/v1/orchestrate/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicV1AskRoute: typeof ApiPublicV1AskRoute
  ApiPublicV1ExecuteRoute: typeof ApiPublicV1ExecuteRoute
  ApiPublicV1OrchestrateRoute: typeof ApiPublicV1OrchestrateRouteWithChildren
  ApiPublicV1PipelineRoute: typeof ApiPublicV1PipelineRoute
  ApiPublicV1DiscoveryRefreshRoute: typeof ApiPublicV1DiscoveryRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/system-flow': {
      id: '/_authenticated/system-flow'
      path: '/system-flow'
      fullPath: '/system-flow'
      preLoaderRoute: typeof AuthenticatedSystemFlowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subtasks': {
      id: '/_authenticated/subtasks'
      path: '/subtasks'
      fullPath: '/subtasks'
      preLoaderRoute: typeof AuthenticatedSubtasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routing-decisions': {
      id: '/_authenticated/routing-decisions'
      path: '/routing-decisions'
      fullPath: '/routing-decisions'
      preLoaderRoute: typeof AuthenticatedRoutingDecisionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests-engine': {
      id: '/_authenticated/requests-engine'
      path: '/requests-engine'
      fullPath: '/requests-engine'
      preLoaderRoute: typeof AuthenticatedRequestsEngineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry': {
      id: '/_authenticated/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AuthenticatedRegistryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orchestrator': {
      id: '/_authenticated/orchestrator'
      path: '/orchestrator'
      fullPath: '/orchestrator'
      preLoaderRoute: typeof AuthenticatedOrchestratorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orchestration': {
      id: '/_authenticated/orchestration'
      path: '/orchestration'
      fullPath: '/orchestration'
      preLoaderRoute: typeof AuthenticatedOrchestrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/network': {
      id: '/_authenticated/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AuthenticatedNetworkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/internal-connectors': {
      id: '/_authenticated/internal-connectors'
      path: '/internal-connectors'
      fullPath: '/internal-connectors'
      preLoaderRoute: typeof AuthenticatedInternalConnectorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fallback-rules': {
      id: '/_authenticated/fallback-rules'
      path: '/fallback-rules'
      fullPath: '/fallback-rules'
      preLoaderRoute: typeof AuthenticatedFallbackRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discovery': {
      id: '/_authenticated/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-console': {
      id: '/_authenticated/api-console'
      path: '/api-console'
      fullPath: '/api-console'
      preLoaderRoute: typeof AuthenticatedApiConsoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites/': {
      id: '/_authenticated/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthenticatedSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipelines/': {
      id: '/_authenticated/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof AuthenticatedPipelinesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites/$slug': {
      id: '/_authenticated/sites/$slug'
      path: '/sites/$slug'
      fullPath: '/sites/$slug'
      preLoaderRoute: typeof AuthenticatedSitesSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipelines/$id': {
      id: '/_authenticated/pipelines/$id'
      path: '/pipelines/$id'
      fullPath: '/pipelines/$id'
      preLoaderRoute: typeof AuthenticatedPipelinesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/v1/pipeline': {
      id: '/api/public/v1/pipeline'
      path: '/api/public/v1/pipeline'
      fullPath: '/api/public/v1/pipeline'
      preLoaderRoute: typeof ApiPublicV1PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orchestrate': {
      id: '/api/public/v1/orchestrate'
      path: '/api/public/v1/orchestrate'
      fullPath: '/api/public/v1/orchestrate'
      preLoaderRoute: typeof ApiPublicV1OrchestrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/execute': {
      id: '/api/public/v1/execute'
      path: '/api/public/v1/execute'
      fullPath: '/api/public/v1/execute'
      preLoaderRoute: typeof ApiPublicV1ExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ask': {
      id: '/api/public/v1/ask'
      path: '/api/public/v1/ask'
      fullPath: '/api/public/v1/ask'
      preLoaderRoute: typeof ApiPublicV1AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/orchestrate/$id': {
      id: '/api/public/v1/orchestrate/$id'
      path: '/$id'
      fullPath: '/api/public/v1/orchestrate/$id'
      preLoaderRoute: typeof ApiPublicV1OrchestrateIdRouteImport
      parentRoute: typeof ApiPublicV1OrchestrateRoute
    }
    '/api/public/v1/discovery/refresh': {
      id: '/api/public/v1/discovery/refresh'
      path: '/api/public/v1/discovery/refresh'
      fullPath: '/api/public/v1/discovery/refresh'
      preLoaderRoute: typeof ApiPublicV1DiscoveryRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedApiConsoleRoute: typeof AuthenticatedApiConsoleRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoveryRoute: typeof AuthenticatedDiscoveryRoute
  AuthenticatedFallbackRulesRoute: typeof AuthenticatedFallbackRulesRoute
  AuthenticatedInternalConnectorsRoute: typeof AuthenticatedInternalConnectorsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedNetworkRoute: typeof AuthenticatedNetworkRoute
  AuthenticatedOrchestrationRoute: typeof AuthenticatedOrchestrationRoute
  AuthenticatedOrchestratorRoute: typeof AuthenticatedOrchestratorRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRoute
  AuthenticatedRegistryRoute: typeof AuthenticatedRegistryRoute
  AuthenticatedRequestsEngineRoute: typeof AuthenticatedRequestsEngineRoute
  AuthenticatedRoutingDecisionsRoute: typeof AuthenticatedRoutingDecisionsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubtasksRoute: typeof AuthenticatedSubtasksRoute
  AuthenticatedSystemFlowRoute: typeof AuthenticatedSystemFlowRoute
  AuthenticatedPipelinesIdRoute: typeof AuthenticatedPipelinesIdRoute
  AuthenticatedSitesSlugRoute: typeof AuthenticatedSitesSlugRoute
  AuthenticatedPipelinesIndexRoute: typeof AuthenticatedPipelinesIndexRoute
  AuthenticatedSitesIndexRoute: typeof AuthenticatedSitesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApiConsoleRoute: AuthenticatedApiConsoleRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoveryRoute: AuthenticatedDiscoveryRoute,
  AuthenticatedFallbackRulesRoute: AuthenticatedFallbackRulesRoute,
  AuthenticatedInternalConnectorsRoute: AuthenticatedInternalConnectorsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedNetworkRoute: AuthenticatedNetworkRoute,
  AuthenticatedOrchestrationRoute: AuthenticatedOrchestrationRoute,
  AuthenticatedOrchestratorRoute: AuthenticatedOrchestratorRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRoute,
  AuthenticatedRegistryRoute: AuthenticatedRegistryRoute,
  AuthenticatedRequestsEngineRoute: AuthenticatedRequestsEngineRoute,
  AuthenticatedRoutingDecisionsRoute: AuthenticatedRoutingDecisionsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubtasksRoute: AuthenticatedSubtasksRoute,
  AuthenticatedSystemFlowRoute: AuthenticatedSystemFlowRoute,
  AuthenticatedPipelinesIdRoute: AuthenticatedPipelinesIdRoute,
  AuthenticatedSitesSlugRoute: AuthenticatedSitesSlugRoute,
  AuthenticatedPipelinesIndexRoute: AuthenticatedPipelinesIndexRoute,
  AuthenticatedSitesIndexRoute: AuthenticatedSitesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiPublicV1OrchestrateRouteChildren {
  ApiPublicV1OrchestrateIdRoute: typeof ApiPublicV1OrchestrateIdRoute
}

const ApiPublicV1OrchestrateRouteChildren: ApiPublicV1OrchestrateRouteChildren =
  {
    ApiPublicV1OrchestrateIdRoute: ApiPublicV1OrchestrateIdRoute,
  }

const ApiPublicV1OrchestrateRouteWithChildren =
  ApiPublicV1OrchestrateRoute._addFileChildren(
    ApiPublicV1OrchestrateRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicV1AskRoute: ApiPublicV1AskRoute,
  ApiPublicV1ExecuteRoute: ApiPublicV1ExecuteRoute,
  ApiPublicV1OrchestrateRoute: ApiPublicV1OrchestrateRouteWithChildren,
  ApiPublicV1PipelineRoute: ApiPublicV1PipelineRoute,
  ApiPublicV1DiscoveryRefreshRoute: ApiPublicV1DiscoveryRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
